# Generated by Django 4.1.6 on 2023-02-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="bookingdate",
            new_name="booking_date",
        ),
    ]
