# Generated by Django 4.1.6 on 2023-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_rename_bookingdate_booking_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
